### PR TITLE
feat(ets-s3): endpoint for deleting files on admin router

### PR DESCRIPTION
**Pull request by viktormarinho**
##### Description of changes

- [x] Why (Why did you make this pull request): endpoint for deleting files on admin router

- [x] Brief description of the changes: Created a simple endpoint that removes a file from the database then from the file system.
- [x] Possible breakouts (Possible places where things could break): Although i tested it on my machine and on windows, i think the fs.rmSync function is kinda suspect. I would keep an eye on every nodejs fs usage because it breaks a lot when changing environment

### CODE REVIEW

**Comment by viktormarinho** [comment]
> Tried to delete a image using the same endpoint for files, it allowed to try it however it threw an error saying that the file was not being deleted but the image was deleted from the table `file`.
> 
> I think this happens because `fs` uses the file metadata prop `path` to delete, however in images the file path (/public/images) is different from the metadata prop `path` (/images) since the endpoint for retrieving images is also `/images`.
> 
> There's two possible solutions right now, either create a new endpoint for deleting images, and verify if the file being deleted is a file or not, if it is, display a proper error message, or change the way image paths are stored in metadata, and use the same endpoint of deleting files for both common files and images.
> 
> Common files (not images) deleting works well and I didn't have any problems whatsoever, an improvement maybe is to make the `prisma` file table mutation and the `fs` mutation (delete the file) to perform a single transaction (meaning that if one of the two mutation fails, all side-effects are reverted) in the same way you can do a database. I believe this provides better error handling and avoid unwanted side-effects (like deleting from file table but not from the filesystem or the opposite).

The image delete not working its solvable with simple string manipulation, and i can use the already stored file type  field to know when to use it. The error that the endpoint returns when you delete a record from the database but not from the file system is not likely to happen at all normally, It Just happens when someone manually deletes a file from the system then after that tries to delete It via the api endpoint. It is more like a error that helps with development.

We can even disable It for production. I Will check the image delete case and fix It.

**Comment by viktormarinho** [comment]
I Will write tests too so we guarantee this bug does not come back

**Comment by abehidek** [comment]
> > Tried to delete a image using the same endpoint for files, it allowed to try it however it threw an error saying that the file was not being deleted but the image was deleted from the table `file`.
> > I think this happens because `fs` uses the file metadata prop `path` to delete, however in images the file path (/public/images) is different from the metadata prop `path` (/images) since the endpoint for retrieving images is also `/images`.
> > There's two possible solutions right now, either create a new endpoint for deleting images, and verify if the file being deleted is a file or not, if it is, display a proper error message, or change the way image paths are stored in metadata, and use the same endpoint of deleting files for both common files and images.
> > Common files (not images) deleting works well and I didn't have any problems whatsoever, an improvement maybe is to make the `prisma` file table mutation and the `fs` mutation (delete the file) to perform a single transaction (meaning that if one of the two mutation fails, all side-effects are reverted) in the same way you can do a database. I believe this provides better error handling and avoid unwanted side-effects (like deleting from file table but not from the filesystem or the opposite).
> 
> The image delete not working its solvable with simple string manipulation, and i can use the already stored file type field to know when to use it. The error that the endpoint returns when you delete a record from the database but not from the file system is not likely to happen at all normally, It Just happens when someone manually deletes a file from the system then after that tries to delete It via the api endpoint. It is more like a error that helps with development.
> 
> We can even disable It for production. I Will check the image delete case and fix It.

Seems fine to me.
What do you think about transforming the current implementation for the mutations (database and filesystem) into a transaction?

**Review by iguoliveira — APPROVED** [review]
After your explaining about the 52 commits in this pr, seems right to let it go

*rich pr*

**Comment by abehidek** [comment]
Lots of good new features, I feel great knowing this repo is getting new things every day.

Code quality is nice, and commits have been well written and organized.

We already discussed about this PR, but once more I will say just to be sure we don't make the same mistake again and to register this moment.

After seeing those commits from a reviewers perspective, we see that this PR:
- Delayed too much every since the conclusion of the proposed feature
- Got out of scope quickly, by changing config files on the monorepo, adding CI testing for all repository, config gitpod et cetera...

And I was pretty much involved on this, and did not worried before, but seeing now, I realized my mistake and I want to sincerely apologize for that. 

From an outsiders perspective, this seems to be a branch for developing quickly and not a branch for a feature as we discussed early on the model.

Looking backwards, it's unproductive to revert this and commit all over again, however, I and others hope that we don't see the same thing happen again in our future.

If anyone wants to discuss about this topic in this PR, feel free to discuss it no hard feelings, I think it's important to talk about this to make sure we are following the right path, and ignoring this type of discussing is not ideal.

Moreover, I don't have anything to talk except congrats for everyone working hard on this project. LGTM 🚀🚀 🌕

**Review by abehidek — APPROVED** [review]

**Pull request merged**
