### PR TITLE
Add semantic commit messages to github/git to docs

### PR DESCRIPTION
**Pull request by vitormiura**
##### Description of changes

- [x] Why (Why did you make this pull request): Add semantic commit messages to github/git intro docs

- [x] Brief description of the changes: docs changes
- [x] Possible breakouts (Possible places where things could break): zero possibilities

### CODE REVIEW

**Review by iguoliveira — APPROVED** [review]
Templates are always good to have.
Nice changes 😁

**Comment by abehidek** [comment]
About the `chore` type, I saw the definition for `grunt tasks`, apparently it means any modification that the user cannot see/use. changes that fit into that category are:
- ci/cd
- development environments configuration and setup
- config files such as `package.json` and `.gitignore`
- et cetera...

I believe it would be clearer to understand if instead of "Tasks pesadas", we could put "Modificação que o usuário não irá ver" and give the above examples, what y'all guys think about this?

**Review by viktormarinho — APPROVED** [review]
nicezada

**Comment by vitormiura** [comment]
> About the `chore` type, I saw the definition for `grunt tasks`, apparently it means any modification that the user cannot see/use. changes that fit into that category are:
> 
> * ci/cd
> * development environments configuration and setup
> * config files such as `package.json` and `.gitignore`
> * et cetera...
> 
> I believe it would be clearer to understand if instead of "Tasks pesadas", we could put "Modificação que o usuário não irá ver" and give the above examples, what y'all guys think about this?

It fitted better, changed just rn

**Pull request merged**
