### PR TITLE
feat(apps): port s3 repo to a /apps project

### PR DESCRIPTION
**Pull request by viktormarinho**
##### Description of changes

- [x] Why (Why did you make this pull request): to port ets-s3 repo into a /apps folder project
- [x] Brief description of the changes: Simply moved the files inside the /apps folder, created a `tsconfig.json` file that extends the new "server.json" config from the tsconfig package. Made sure that the service is running and utilizing the environment variables correctly.
- [x] Possible breakouts (Possible places where things could break): The new `server.json`  file at the `tsconfig` package. I created this file to have the same options as the tsconfig from the "auth-server" app, but when i tested extending it in the auth-server app it failed. So i just switched back to before. This file is only being used by the ets-s3 app. It is working, but i dont think it is finished and good to go to use on other servers. Will create the server example later, probably after modifying this `server.json ` file.

Important: There are file changes at the #3 that were needed for me to keep developing the feature (and i did not had access to them, since my base branch was dev and #3  hasn't been merged yet), even though they are not part of the PRs feature, but i could make a workaround. ( `.env.dev`  changes) .

Let's try to keep PRs containing only the file changes that they were created for, so we don't have this problems when developing with more people. Just a reminder for myself and everyone

### CODE REVIEW

**Comment by abehidek** [comment]
About the TSConfig file:

I think there's no problem regarding the `server.json` itself, I think that because `server.json` is extending the `base.json` file, it merges some it's properties which makes TypeScript angry about some codes, for example, I see that in the file `apps/ets-s3/src/routers/image.ts`, we have this code:

```ts
export default { router };
```

However TS get's angry saying:
```error
The inferred type of 'default' cannot be named without a reference to 
'.pnpm/@types+express-serve-static-core@4.17.31/node_modules/@types/express-serve-static-core'. 
This is likely not portable. A type annotation is necessary.ts(2742)
```

However, after by assigning true to the option `compilerOptions.declaration: false` in the `base.json` tsconfig file, the TS error simply vanishes (I think this happens because by exporting an anonymous object as default, TS cannot convert into a `.d.ts` file

**Comment by abehidek** [comment]
And also, I agree about the last sentence, one PR should not intefere with another PR, but if PR depends on another, merge the first PR into dev, then merge these changes into the second PR

**Comment by abehidek** [comment]
However, again about the TSConfig, probably it's better do this in another PR in which se setup correctly the `TSConfig` package for all servers and not this one which the main purpose is to port the `ets-s3` server into our monorepo as a project.

**Review by abehidek — COMMENTED** [review]
LGTM, let's do the TSConfig thing in another PR (Probably will be the server template one), going to create it on ClickUp and assign us to make it

**Review by abehidek — APPROVED** [review]
Forgot to approve it lmao

**Comment by vitormiura** [comment]
> And also, I agree about the last sentence, one PR should not intefere with another PR, but if PR depends on another, merge the first PR into dev, then merge these changes into the second PR

For now I think that is the best method too, because it will have a lot of PRs depending on others to works fine in dev env.

**Review by vitormiura — APPROVED** [review]
lgtm to me for now, waiting the `TSConfig`  and client to do some pocs to test it👍

**Pull request merged**
