### PR TITLE
CU-864dkuhz9 - refactor(all servers): tsnode/tsnode-dev -> tsx

### PR DESCRIPTION
**Pull request by abehidek**
##### Description of changes

- [x] Why (Why did you make this pull request): To improve build times and DX experience in monorepo.
- [x] Brief description of the changes: Uninstall ts-node/ts-node/tsconfig-paths deps in all servers (including server-template)
- [x] Possible breakouts (Possible places where things could break): tsx uses esbuild under the hood which has [some caveats](https://esbuild.github.io/content-types/#javascript-caveats), however all of them should not break or disrupt anything.

Just in case, before merging this PR, test if your operating system handles that.

### CODE REVIEW

**Comment by abehidek** [comment]
Tests went good on docker inside NixOS

**Review by viktormarinho — APPROVED** [review]
Works on my machine!

**Comment by abehidek** [comment]
**Do not merge this yet**, I'm removing some bad option flags from all `package.json`.

**Comment by abehidek** [comment]
New changes seems to be working well with [tsx](https://github.com/esbuild-kit/tsx) on Windows and in Docker inside Linux, ready for review @iguoliveira and @vitormiura !!

**Review by vitormiura — APPROVED** [review]
working fine as hell in arch wsl

**Comment by vitormiura** [comment]
wait to @iguoliveira or just merge rn?

**Comment by abehidek** [comment]
Let me fix and verify the conflict between `dev` and `CU-864dkuhz9_tsnode-to-tsx_abehidek`, apparently, because of the merge of the documentation in dev, this pr got some conflicts on the `pnpm-lock.yaml` file

**Comment by abehidek** [comment]
Seems fine now, before merging, @viktormarinho and @vitormiura, can you guys just try to run again to see if anything fails?, probably it will run fine

**Comment by viktormarinho** [comment]
All ok! can i merge it rn? Need to update main branch asap. It is too old and does not have the same structure as the dev one

From now on we should be pushing consistent releases to there

**Pull request merged**
