### PR TITLE
Cu 864e4g75q borum integration backend - DO NOT MERGE YET!!!!!

### PR DESCRIPTION
**Pull request by eduardo-victor**
##### Description of changes

- [x] Why (Why did you make this pull request): To add functionality to the add classes and classes page

- [x] Brief description of the changes: Created a new file called adicionaraula.tsx which have some functions to add classes
- [x] Possible breakouts (Possible places where things could break): 0 for now

### CODE REVIEW

**Comment by vitormiura** [comment]
do not merge yet @viktormarinho @iguoliveira @abehidek, working in progress here.

**Comment by vitormiura** [comment]
changes coming, do not merge! @viktormarinho @abehidek @iguoliveira

**Review by viktormarinho — APPROVED** [review]
:100: lets go

**Review by vitormiura — APPROVED** [review]
seems to be fine rn 👍

**Pull request merged**
