### PR TITLE
General file upload w/ compression & auth

### PR DESCRIPTION
**Pull request by viktormarinho**
##### Description of changes

- [x] Why (Why did you make this pull request): General file upload w/ compression & auth

- [x] Brief description of the changes: 
    - Created general file upload router that contains 2 endpoints: One for uploading any file (compressed
    and then stored) and other for retrieving (decompressed and then returned)
    - Made some tests with Insomnia
- [x] Possible breakouts (Possible places where things could break): The compression is definetively NOT SUITABLE for production. I haven't tested all the major file formats that we need to support. IT NEEDS more tests to be considered ok.
What i have tested is:
    - PDF upload (working perfectly) compression and decompression, storing the size with only about 55% the original size.
    - MP4 upload (working, but not very well). I tested uploading a 1h45 (177MB) video. Compressed, it still had 171 MB of size. Maybe gzip is not good at compressing video? I can easily try to change it to brotli later, or maybe make a reserved endpoint for videos. Besides that, the decompressed video seemed to be fine and apparently no quality was lost.

**MORE CHANGES WERE MADE:**

- File decompression responsibility moved to the browser. Now i only pass a Content-Encoding Header.
- Two GET endpoints on file router: One for downloading a file with a given ID, and another for retrieving all that file data. (the second one gives the downloadUrl, so it is really handy to use when you want the file metadata and the download)
- Created the admin router that atm only have a single endpoint that returns all files
-  Removed incorrect metadata parsing from the backend
- Changed the SDK so it parses/stringifies Meta when needed and throws errors when doing it goes wrong as well
- Added the File.retrieve function to the SDK, with a optional generic Metadata type, making even the meta attribute typesafe if you want
- Now exporting useful types from the SDK lib as well
- New Vite Mock tests, using the SDK file retrieve, Metadata utilization & the new Metadata generic

### CODE REVIEW

**Review by vitormiura — APPROVED** [review]
lgtm, live reviewed

**Comment by viktormarinho** [comment]
**Please do not merge this right now**. I will be making more commits for optimization, cleaner code and a new feature support.

**Comment by abehidek** [comment]
When ready, please comment below @viktormarinho

**Comment by viktormarinho** [comment]
All OK Now! But please re-read what i have added in the PR description (#14 )! I think it is finished now haha

**Comment by abehidek** [comment]
Code overall looks pretty good, quite good the `errorMessages` object in the file router. Metadata handling seems straightforwardas well.

I commited a small thing regarding the usage of environment variables, providing a fallback in case `VITE_SERVICE_S3_URL` is not provided.

Working well on docker inside NixOS, going to test on windows before merging.

**Review by abehidek — APPROVED** [review]
Forgot to test the admin router from insomnia, working good as well.

Also, finished testing on Windows, everything went good, merging this right now.

**Pull request merged**
