### PR TITLE
Cu 864dkyd4t feat list all users admin endpoint and setup tests for auth abehidek

### PR DESCRIPTION
**Pull request by abehidek**
##### Description of changes

- [x] Why (Why did you make this pull request): Make this endpoint accessible for admin users, in which they can view all users with maximum detail.

- [x] Brief description of the changes: 
  - Add new endpoint to router file, which uses the created middleware for authorizing if the user is Admin.
  - Change sign out endpoint http method from POST to DELETE.
  - Update thunder client docs
  - Add tests for the newly added endpoint and for other endpoints as well
- [x] Possible breakouts (Possible places where things could break): No breakout found since no other code uses this endpoint before.

### CODE REVIEW

**Comment by abehidek** [comment]
Just commenting the fact that the CI steps for this pull request did the same thing as stated on #31 pull request:

- Docs CI went well (since no changes have been made).
- On Push CI did not have any problems.
- On Pull request failed initially due to a problem during `pnpm setup-repo` cmd, but after re-running it executed all jobs without problems. 

Anyway, worth observing this behavior and see if the same thing happen over and over again

**Review by viktormarinho — CHANGES_REQUESTED** [review]
it would be good to have tests ensuring the functionality of these endpoints

**Comment by abehidek** [comment]
Will do the tests asap

**Comment by abehidek** [comment]
@viktormarinho @vitormiura @iguoliveira tests ready!, I think it's good to approve this

It's important to add tests for added features, it makes you reason about your own code and improve their quality.

**Review by vitormiura — APPROVED** [review]
important endpoint and clean tests, already ran in my machine and worked fine 👍

**Review by viktormarinho — APPROVED** [review]
lgtm!!!

**Pull request merged**
