### PR TITLE
Release 0.0.0 (Start)

### PR DESCRIPTION
**Pull request by viktormarinho**
##### Description of changes

- [x] Why (Why did you make this pull request): Start the release cycle

- [x] Brief description of the changes: There are a lot of changes but they are all well documented by its PRs and Commits. (Although i think all releases should list the new features from now on)
- [x] Possible breakouts (Possible places where things could break): There are missing tests for most things in the repo! those are coming soon

### CODE REVIEW

**Review by iguoliveira — APPROVED** [review]
Leeroyy jenkinsss!!

Nice.

**Review by vitormiura — APPROVED** [review]
code solid asf 👍, btw needs to see docs and einer ci/cd

**Comment by abehidek** [comment]
Gonna try to solve the CI issues before merging to main, and try to test other things.

**Comment by viktormarinho** [comment]
Vercel is buggy it seems! the deployment just said it failed on top of the checks, but on the checks everything worked and is green!

**Review by abehidek — APPROVED** [review]
Guess we can now merge this to main without problems whatsoever. But it's also interesting to make sure all `servers` are built as well using `tsup`, and deployed together with other apps and services to the SENAI and ETS servers through a CD pipeline in the next release, @DaniHRE will be a key person to do that since we need to understand better the build artifact created by turbo, and research a way to run inside a docker, and then run inside a CD pipeline in caprover, I will try to help as much as possible in that way.

Anyway, I am really proud of this project and I hope we can attend all expectations that are upon us, and learn along the way. Good Job @ets-einer/everyone 🚀

**Pull request merged**
