### PR TITLE
CU-864ed5yfp: luciano service

### PR DESCRIPTION
**Pull request by abehidek**
##### Description of changes

- [x] Why (Why did you make this pull request): To have a centralized notification system between apps

- [x] Brief description of the changes:
    - Add environment variables for luciano
    - Add service luciano to apps
    - Add /notifications page in web-common for all notifications
    - Add @luciano/client package
    - Add Notification.tsx component in ui/Navbar.tsx
    - Change db:setup global scripts to db:setup turborepo script (same script for all applications for more granular control e.g `pnpm db:setup --filter=luciano`)
    -  Add bell.svg icon to assets/icons folder in ets-s3
- [x] Possible breakouts (Possible places where things could break):
    - db:setup script (almost sure it will not break)
    - seedUsers (remove explicit types to `as const` to make typescript knows the size of that array and thus eliminating the need for optional chaining)

### CODE REVIEW

**Comment by abehidek** [comment]
Wait for @viktormarinho review

**Comment by viktormarinho** [comment]
We need to update the UI to match the rest of our interface
Besides that, its approved for me

**Comment by abehidek** [comment]
@viniciusventura29 can you help in doing so?

**Comment by viniciusventura29** [comment]
> @viniciusventura29 can you help in doing so?
Of sure! Yesterday I just ran this branch and thought in some things that we could do

**Review by viniciusventura29 — COMMENTED** [review]
it's very good!

**Review by viniciusventura29 — APPROVED** [review]

**Review by vitormiura — APPROVED** [review]

**Pull request merged**
