### PR TITLE
Cu 864dvjde6 sidebar planner elizeu

### PR DESCRIPTION
**Pull request by elizeumagalhaes**
##### Description of changes

- [x] Why (Why did you make this pull request):  Finished planner sidebar

- [x] Brief description of the changes: Finished planner sidebar ready to be converted to global
- [x] Possible breakouts (Possible places where things could break): Possible breakout when trying to pass icon buttons through props

### CODE REVIEW

**Review by iguoliveira — APPROVED** [review]
Seems good!
It'll be tested in dev with the beggin of planner development, there, we can find possible errors with dimensions and stuff
Althoug, very good! 😁

**Comment by vitormiura** [comment]
do not merge @abehidek @iguoliveira @viktormarinho, adding component class variants soon.

**Review by gustavobaltazar — APPROVED** [review]
Seems clean fag!

**Review by abehidek — APPROVED** [review]
lgtm

**Pull request merged**
