### PR TITLE
Test monorepo ci and docs cd abehidek

### PR DESCRIPTION
**Pull request by abehidek**
## DO NOT MERGE THIS PR, JUST FOR TESTING PURPOSES

- [x] Why (Why did you make this pull request): test CI and CD pipelines

- [x] Brief description of the changes: Only changes in `README.md` to make sure CI and CD is indeed building correctly several times
- [x] Possible breakouts (Possible places where things could break): Nothing

### CODE REVIEW

**Comment by abehidek** [comment]
Created this PR to test the `on pull_request` action pipeline

**Comment by abehidek** [comment]
lmao

**Comment by abehidek** [comment]
@viktormarinho @iguoliveira @vitormiura, I have some interesting things to say

There was just one test where the `on pull_request` action has failed, however, after clicking to re-run all jobs, the CI completed successfully without problems (which is the reason why now all commits have their checks passed.

In other side, the `on push` action seems to be more accurate, whenever something is really wrong, both `on pull_request` and  `on push` fails as well, however if everything is fine, `on push` never fails, but `on pull_request` seems to fail sometimes for whatever reason, but after re-running `on pull_request` action, it suddenly finishes all the jobs successfully. 

The reason of this probably lies in some weird interaction between the caching provided by turbo and the github actions workers, or maybe github actions isn't as stable as we thought, or maybe some weird code is causing this behaviour.

But to finally finish this thread and continue developing, I suggest continuing to have both `on pull_request` and  `on push` actions, however if only the `on pull_request` for some reason fails, we try to re-run it to be sure.

Tell y'all guys what do you think.

**Comment by viktormarinho** [comment]
> 

All nice to me! 

Although, we have to continue to keep an eye in the pipelines. Here, the only thing changed was the README.md file, and if we have a suspect that some pnpm and gh actions caching interactions could be causing this, it can come to happen again.

Anyways, re-running PR CI when something seems off is prob the overall best action to take from now on

gj

**Comment by abehidek** [comment]
No problems found whatsoever, CI seems to be working fine, if CI stop working, we solve it by creating a new PR.

**Pull request closed without merging**
