### PR TITLE
Cu 864dvjmx2 setup monorepo cap rover

### PR DESCRIPTION
**Pull request by DaniHRE**
@abehidek @iguoliveira @vitormiura @viktormarinho 

##### Description of changes

- [x] Why (Why did you make this pull request): I Make this pull request to create necessary files to setup deploy environment in CapRover PasS aplication.

- [x] Brief description of the changes: Dockerfiles to static pages, and captain-definition files to entrypoint.
- [x] Possible breakouts (Possible places where things could break): Inside Dockerfile in npm download scripts, easy to solve if t break.

### CODE REVIEW

**Comment by DaniHRE** [comment]
@abehidek @iguoliveira @viktormarinho @vitormiura 
Don't merge project now, wait

**Comment by DaniHRE** [comment]
@vitormiura @abehidek @iguoliveira @viktormarinho 
Ready to merge, working fine.

**Review by vitormiura — APPROVED** [review]
looking solid, hope its works in ets "server" 👍

**Comment by abehidek** [comment]
**Do not merge this yet**, I've talked to @DaniHRE and since the server build pr #49 is now merged into dev and consequently into this branch, he now can take the server build and try to deploy it to caprover.

**Review by vitormiura — APPROVED** [review]
clean 💯

**Pull request merged**
