### PR TITLE
Cu 864evx07j welcome modal ventura

### PR DESCRIPTION
**Pull request by viniciusventura29**
##### Description of changes

- [X] Why (Why did you make this pull request): Creating welcome modal!

- [X] Brief description of the changes: If user never access the website, a modal will appear.
- [X] Possible breakouts (Possible places where things could break):

### CODE REVIEW

**Review by vinicius-prates — APPROVED** [review]
gtg

**Comment by viktormarinho** [comment]
Please add back the console.log s in the "log" package.

Another point: we REALLY need to talk about those auto format/lint on save tools

Besides that the feature is really nice!

**Review by vinicius-prates — COMMENTED** [review]
just typing the logs over again hahaha 👍🏼

**Review by viktormarinho — APPROVED** [review]
Im a lil afraid of the user type, but it seems okay!

beautiful introduction for our users :)

**Pull request merged**
