### PR TITLE
Cu 864e7utyz common global dropdown

### PR DESCRIPTION
**Pull request by vitormiura**
##### Description of changes

- [x] Why (Why did you make this pull request): make dropdown global

- [x] Brief description of the changes: add global dropdown component
- [x] Possible breakouts (Possible places where things could break): nothing!

### CODE REVIEW

**Comment by abehidek** [comment]
Is this ready for merging?

**Comment by vitormiura** [comment]
> Is this ready for merging?

I think it is, waiting to see if attends @viktormarinho expectations, cuz the component is just receiving a list as props

**Review by viktormarinho — CHANGES_REQUESTED** [review]
I think there needs to be a way for the component to pass the data (the selected field onchange) up!

I also think it could be nice to pass a object array containing display values and Id values.
The intention is when i click a display value the component then triggers a callback with the Id of the selected value. 

This way the component can be used efficiently by other appllications.

**Comment by vitormiura** [comment]
> I think there needs to be a way for the component to pass the data (the selected field onchange) up!
> 
> I also think it could be nice to pass a object array containing display values and Id values. The intention is when i click a display value the component then triggers a callback with the Id of the selected value.
> 
> This way the component can be used efficiently by other appllications.

aight, changes in coming, do not merge yet!

**Review by abehidek — COMMENTED** [review]
???? 👿 GRR

**Review by viniciusventura29 — APPROVED** [review]
Now its Gtg for me ! 🚀

**Review by viniciusventura29 — APPROVED** [review]
Nice!!

**Review by viktormarinho — APPROVED** [review]
rust
good to go :)

**Pull request merged**
